# Common_vars
availability_zone: melbourne-qh2

# Volume
volumes:
  - vol_name: demo-vol-docker
    vol_size: 10
  - vol_name: demo-vol-data
    vol_size: 20

# Security group
security_groups:
  - name: demo_ssh
    description: "demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: demo_http
    description: "demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

# Instance 
instance_name: demo
instance_image: 0a2bac09-8beb-464a-9cbc-6adf4dfcd5e5
instance_key_name: cloud
instance_flavor: uom.general.2c8g

